outsider_press-momfeed:
    download_dir: /media/mastertaku/ext_storage/media/mom
    rss: https://rss.outsider.press/public.php?op=rss&id=2809&key=vyil9q5e84f8ced4573
outsider_press-interesting:
    rss: https://rss.outsider.press/public.php?op=rss&id=-1460&key=xexmt25ec46090f2c8c
    download_dir: /media/mastertaku/ext_storage/media/interesting-videos
mylist:
    rss: https://rss.outsider.press/public.php?op=rss&id=-1467&key=ejvjwe5faf8c0d2a053
    download_dir: /media/mastertaku/ext_storage/media/MY_DOWNLOADS
spitting-image:
    rss: https://www.youtube.com/feeds/videos.xml?channel_id=UCCov3Uxwgh6Fq_2F7oW9-hA
    download_dir: /media/mastertaku/ext_storage/media/SpittingImage
    filter: "Full Episode"
ShowMustGoOn:
    rss: https://www.youtube.com/feeds/videos.xml?channel_id=UCdmPjhKMaXNNeCr1FjuMvag
    download_dir: /media/mastertaku/ext_storage/media/Live Plays
    filter: 
        - "FULL STAGE SHOW"
        - "FULL SHOW"
        - "FULL STAGE PLAY"
QI-XL:
    rss: https://www.youtube.com/feeds/videos.xml?channel_id=UCNWdtlXduDBmKq3QHqlEg-g
    download_dir: /media/mastertaku/ext_storage/media/QI
    filter: "QI XL"
NationalTheater:
    rss: https://www.youtube.com/feeds/videos.xml?channel_id=UCUDq1XzCY0NIOYVJvEMQjqw
    download_dir: /media/mastertaku/ext_storage/media/Live Plays
    filter: "Full Performance"
StratfordFestival:
    rss: https://www.youtube.com/feeds/videos.xml?channel_id=UC_1Ricuv8kk5oUwJn4K4r7Q
    download_dir: /media/mastertaku/ext_storage/media/Live Plays
    filter: "LIVE VIEWING PARTY"
ShakespearsGlobe:
    rss: https://www.youtube.com/feeds/videos.xml?channel_id=UCwN-jwNNNQN-8sfKG-qg8uA
    download_dir: /media/mastertaku/ext_storage/media/Live Plays
    filter: 
        - "Globe Advent"
        - "for Free"
Mundo-HOG:
    rss: https://www.youtube.com/feeds/videos.xml?channel_id=UCq_ZoGyeCb-1nUCD9z8Fzcg
    download_dir: /media/mastertaku/ext_storage/media/House of Games
    filter: "House of Games"
Gazebo-8O10C:
    rss: https://www.youtube.com/feeds/videos.xml?channel_id=UCXE4voyN9idmfk6eXXDarVQ
    download_dir: /media/mastertaku/ext_storage/media/Countdown
    filter: "8 Out Of 10 Cats Does Countdown"
Gazebo-HIGNFY:
    rss: https://www.youtube.com/feeds/videos.xml?channel_id=UCXE4voyN9idmfk6eXXDarVQ
    download_dir: /media/mastertaku/ext_storage/media/HIGNFY
    filter: "Have I Got News For You"
Gazebo-TLL:
    rss: https://www.youtube.com/feeds/videos.xml?channel_id=UCXE4voyN9idmfk6eXXDarVQ
    download_dir: /media/mastertaku/ext_storage/media/The Last Leg
    filter: "The Last Leg"
OVID-MTW:
    rss: https://www.youtube.com/feeds/videos.xml?channel_id=UC_SFqM6PCAh7N3A4NkCA0cw
    download_dir: /media/mastertaku/ext_storage/media/MTW
    filter: "Mock the Week"
RussellHoward:
    rss: https://www.youtube.com/feeds/videos.xml?channel_id=UCnLxFpGiCi-u3RLx9uF8bOg
    download_dir: /media/mastertaku/ext_storage/media/Russell Howard
    filter: 
        - "Full Episode"
        - "Full Compilation Episode"
Python:
    rss: https://rss.outsider.press/public.php?op=rss&id=-1468&key=ejq9f75fe7d1208f096
    download_dir: /media/mastertaku/ext_storage/media/Computer Videos/Python
Nashville:
    rss: https://rss.outsider.press/public.php?op=rss&id=-1469&key=6563zy5fe8c333ce988
    download_dir: /media/mastertaku/ext_storage/media/Nashville
